### PR TITLE
[Feature] add url of package, pretty json output

### PR DESCRIPTION
**Pull request by lukepistrol**
I don't know whether you accept contributions but I recently found this project and thought it'd be nice to have some additions. (Otherwise just close this PR)

### Repository URL

I added a new `url` property to `OutdatedPackage` in order to also display that in the output.

This way one can easily command-click the link from their terminal and open the repository in their browser.

It looks like this:

Screenshot 2023-06-02 at 20 11 45

And in Xcode:

Screenshot 2023-06-02 at 20 18 43

### Pretty Printed JSON

I also added an option `prettyJSON` to the `OutputFormat` enum for a more *human-readable* json output.

It can be invoked using:

```bash
swift outdated -f pretty-json
```

… and looks like this:

Screenshot 2023-06-02 at 20 17 04

### CODE REVIEW

**Comment by kiliankoe** [comment]
Hey @lukepistrol, this seems like a great addition, thank you!

Do you think it's worth it to have both JSON and pretty-printed JSON as output formats? I don't think there's much of a reason to keep "unpretty" (ugly? lol) JSON around, we might as well just always pretty-print it. I don't think it makes a difference for any tooling that one would build on top of this and the (*very* minor) performance hit is negligible compared to the time the version fetching takes beforehand.
Imo feel free to set the output formatting flag on the normal JSON encoder and consolidate those. 

The URL is a great idea as well, totally makes sense to have that be quickly accessible 👍

**Comment by lukepistrol** [comment]
> Do you think it's worth it to have both JSON and pretty-printed JSON as output formats?

@kiliankoe actually, no. The performance difference is indeed pretty small and I cannot think about a tool that can't handle both options.

I will replace it shortly.

**Comment by kiliankoe** [comment]
Looks great, thank you!

**Comment by kiliankoe** [comment]
I've just tagged version 0.5.0 and updated the homebrew formula, thanks again for the contribution :)

**Pull request merged**
